## NumPy
is a fundamental library for scientific computing in python. it provides support for arrys and matrices along with a collection of mathematical functions to operate on these data structues. in this lesson we wil cover the basic of NumPy focusing on arrays and vectorized operations..

In [4]:
import numpy as np


In [10]:
#create an array
#create 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
print(type(a))
print(a.shape)
#here we have single dimension

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)


In [21]:
#reshape in 2D
a2 = a.reshape(2, 5) #2row and 5 column
print(a2)
print(a2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [23]:
arr=np.array([[1,2,3,4,5,6]])#1D array
print(arr)
print(arr.shape)
print(type(arr))

[[1 2 3 4 5 6]]
(1, 6)
<class 'numpy.ndarray'>


In [24]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])#2D array
print(arr)
print(arr.shape)
print(type(arr))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
<class 'numpy.ndarray'>


In [27]:
np.arange(0, 10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [30]:
np.ones((3,4))#3 row and 4 column 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
#ATTRIBURES OF NumPy  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("number of dimensions:", arr.ndim)
print("Size(number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Itemsize(in bytes):", arr.itemsize)


Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
number of dimensions: 2
Size(number of elements): 8
Data type: int64
Itemsize(in bytes): 8


In [42]:
#numpy vectorzed operation
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

#element wise addition
print("Addition:",arr1+arr2)

#element wise subtraction   
print("Subtraction:",arr1-arr2)

#element wise multiplication
print("Multiplication:",arr1*arr2)

#element wise division
print("Division:",arr1/arr2)

#element wise power
print("Power:",arr1**arr2)

#element wise modulo
print("Modulo:",arr1%arr2)

#output also in array


Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Power: [                   1              1048576      205891132094649
                    0 -6776596920136667815]
Modulo: [1 2 3 4 5]


In [45]:
#unverisal function
arr= np.array([1,2,3,4,5])
#square root
print(np.sqrt(arr))
#exponential
print(np.exp(arr))
#sine
print(np.sin(arr))
#nature logarithm
print(np.log(arr))
#logarithm
print(np.log10(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [56]:
#array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:


print(arr[1:,2:])
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,1:3])

[[ 7  8]
 [11 12]]
1
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [68]:
##modify array elements
arr[0,0]=100

In [69]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [70]:
arr[1:]=100
print(arr)


[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [73]:
#statistical concepts - normaliozation
#to have a mean of 0 and std of 1
data = np.array([1,2,3,4,5,])

#calculate mean ans standard deviation
mean = np.mean(data)
std = np.std(data)

print(mean)
print(std)

#normalize
normalized = (data-mean)/std
print("normalized data:",normalized)


3.0
1.4142135623730951
normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [85]:
#mean
mean = np.mean(data)
print("mean: ",mean)
#mode
mode = np.median(data)
print("mode: ",mode)
#meadian
median = np.median(data)
print("median:",median)
#variance
variance = np.var(data)
print("variance:",variance)
#standard deviation
std = np.std(data)
print("Standard deviation:",std)


mean:  3.0
mode:  3.0
median: 3.0
variance: 2.0
Standard deviation: 1.4142135623730951


In [93]:
#logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])


In [95]:
data[(data>=5) & (data<=8)]


array([5, 6, 7, 8])